# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  taskSuffix: ''
  enabledTasks:
    buildGo: true
    buildGradle: true
    buildPython: true
    buildTypescript: true
    packageImage: true
    deployHelm: true

registry: image-registry.openshift-image-registry.svc:5000
namespace: ods
pushRegistry: image-registry.openshift-image-registry.svc:5000
