kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-start
spec:
  output:
    to:
      name: 'ods-start:0.1.0'
  source:
    git:
      uri: https://github.com/opendevstack/ods-pipeline
      ref: v0.1.0
