apiVersion: v1
kind: Secret
metadata:
  name: ods-sonar-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  password: '{{ .Values.AuthToken }}'
  username: '{{ .Values.sonarUsername }}'
type: kubernetes.io/basic-auth
