apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ods-finish-v0-1-0
spec:
  description: Finishes the pipeline
  params:
    - default: "localhost:5000/ods/finish:latest"
      description: The location of the image.
      name: image
      type: string
    - description: Web console URL
      name: console-url
      type: string
    - description: name of pipeline run
      name: pipeline-run-name
      type: string
    - name: aggregate-tasks-status
      description: The aggregate status of all the tasks.
      default: "None"
  steps:
    - # default image: build/package/Dockerfile.finish
      image: $(params.image)
      name: ods-finish
      env:
        - name: NEXUS_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: nexus
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: nexus-auth
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: nexus-auth
        - name: BITBUCKET_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: bitbucket
        - name: BITBUCKET_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: bitbucket-auth
      resources: {}
      workingDir: $(workspaces.source.path)
      script: |

        # ods-finish is built from cmd/finish/main.go.
        ods-finish \
          -console-url=$(params.console-url) \
          -pipeline-run-name=$(params.pipeline-run-name) \
          -aggregate-tasks-status=$(params.aggregate-tasks-status)

  workspaces:
    - description: The git repo will be present onto the volume backing this workspace
      name: source
