kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-pipeline-manager
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-pipeline-manager:{{.Values.global.imageTag}}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: imageTag
          value: '{{.Values.global.imageTag}}'
  source:
    dockerfile: |-
      {{- .Files.Get "docker/Dockerfile.pipeline-manager" | nindent 6}}
  runPolicy: Serial
