{{if or .Values.global.enabledTasks.buildPython .Values.pythonToolset }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-python-toolset
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-python-toolset:{{.Values.global.imageTag}}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
        - name: imageTag
          value: '{{.Values.global.imageTag}}'
  source:
    dockerfile: |-
      {{- .Files.Get "docker/Dockerfile.python-toolset" | nindent 6}}
  runPolicy: Serial
{{end}}
