kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ods-webhook-interceptor
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ods-webhook-interceptor:{{.Values.imageTag}}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: build/package/Dockerfile.webhook-interceptor
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi8/ubi-minimal:8.4'
      buildArgs:
        - name: taskKind
          value: '{{default "ClusterTask" .Values.taskKind}}'
        - name: taskSuffix
          value: '{{.Values.taskSuffix}}'
      pullSecret:
        name: registry.redhat.io
  postCommit: {}
  source:
    type: Git
    git:
      uri: '{{.Values.odsPipelineGitRepoUri}}'
      ref: '{{.Values.odsPipelineGitRepoRef}}'
  runPolicy: Serial
