# Bitbucket
# Bitbucket personal access token (PAT) in clear text. This token needs to be
# created in Bitbucket for the user identified by "bitbucketUsername".
# The user requires write permissions in order to set build status or add code
# insights on commits.
bitbucketAccessToken: ''
# Shared secret between webhooks in Bitbucket and the event listener. Create
# a random secret and enter it here, then use it later on as the secret in any
# webhook you setup. The value needs to be in clear text.
bitbucketWebhookSecret: ''

# Nexus
# Nexus password for the user identified by "nexusUsername" in clear text.
nexusPassword: ''

# Sonar
# SonarQube password for the user identified by "sonarUsername" in clear text.
sonarAuthToken: ''

# Aqua
# Aqua password for the user identified by "aquaUsername" in clear text.
# Leave empty when not using Aqua.
aquaPassword: ''

# Aqua
# URL to download aqua-scanner binary. The URL must contain basic authentication.
aquasecScannerUrl: ''
